### ISSUE TITLE
Bị checkpoint

### ISSUE THREAD

**Issue by vienntbna** [locmai0808/Facebook-Access-Token#1]
Mình chạy thì nó có ra token nhưng khi vào lại facebook thì bị checkpoint b a. Có cần chú ý gì ko ? Mình đã chạy trên cùng máy với facebook đang đăng nhập. Tài khoản mình có bảo mật 2 lớp và mình đã dùng App password

**Comment by locmai0808** [comment]
@vienntbna: De minh xem lai nhe.
