### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by pretech86** [locmai0808/Facebook-Access-Token#2]
> facebook-access-token@1.0.0 start /usr/share/Facebook-Access-Token
> node index.js

/usr/share/Facebook-Access-Token/token.js:6
async function getToken(email, password) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/share/Facebook-Access-Token/index.js:2:18)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

npm ERR! Linux 4.19.0-kali4-amd64
npm ERR! argv "/root/.nvm/versions/node/v4.2.6/bin/node" "/root/.nvm/versions/node/v4.2.6/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! facebook-access-token@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the facebook-access-token@1.0.0 start script 'node index.js'.
npm ERR! This is most likely a problem with the facebook-access-token package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls facebook-access-token
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/share/Facebook-Access-Token/npm-debug.log

**Comment by locmai0808** [comment]
`npm ERR! node v4.2.6
npm ERR! npm v2.14.12`

Try updating both your node and npm version.

**Comment by pretech86** [comment]
How can i do this ?

**Comment by pretech86** [comment]
thanks it working well
